<?php
/**
 * Pantalla "Integridad de firmas" (admin/signature-integrity.php). Variables: $enabled, $uses_config,
 * $current_key_id, $current_key, $stored, $last, $legacy, $notice, $count, $date, $user_name.
 */
if (!defined('ABSPATH')) exit;

$form = static function (string $action, string $label, string $class = 'button', string $confirm = ''): void {
    ?>
    <form method="post" action="<?= esc_url(admin_url('admin-post.php')) ?>" style="display:inline-block"
        <?= $confirm ? 'onsubmit="return confirm(' . esc_attr(wp_json_encode($confirm)) . ');"' : '' ?>>
        <input type="hidden" name="action" value="<?= esc_attr($action) ?>">
        <?php wp_nonce_field($action); ?>
        <button type="submit" class="<?= esc_attr($class) ?>"><?= esc_html($label) ?></button>
    </form>
    <?php
};
?>
<div class="wrap">
    <h1><?= esc_html__('Signature integrity', 'wp-certificates') ?></h1>
    <p><?= esc_html__('Evidence of the signatures: every new signature is sealed with a fingerprint chained to the previous one, so any later change or deletion in the database can be detected.', 'wp-certificates') ?></p>

    <?php if ('verified' === $notice) : ?>
        <div class="notice notice-success is-dismissible"><p><?= esc_html__('Verification completed.', 'wp-certificates') ?></p></div>
    <?php elseif ('rotated' === $notice) : ?>
        <div class="notice notice-success is-dismissible"><p><?= esc_html__('A new key was created. New signatures use it; previous signatures are still verified with their own key.', 'wp-certificates') ?></p></div>
    <?php endif; ?>

    <?php if (!$enabled) : ?>
        <div class="notice notice-warning"><p><?= esc_html__('The database has not been updated yet. An administrator must open the admin once so the update runs; until then signatures are saved without fingerprint.', 'wp-certificates') ?></p></div>
    <?php else : ?>

    <h2><?= esc_html__('Signing key', 'wp-certificates') ?></h2>
    <table class="widefat striped" style="max-width:760px">
        <tbody>
            <tr>
                <th scope="row"><?= esc_html__('Active key', 'wp-certificates') ?></th>
                <td><code><?= esc_html($current_key_id ?: '—') ?></code></td>
            </tr>
            <tr>
                <th scope="row"><?= esc_html__('Level', 'wp-certificates') ?></th>
                <td><?= $uses_config
                    ? esc_html__('Reinforced: key defined in wp-config.php', 'wp-certificates')
                    : esc_html__('Automatic: key generated by the plugin and stored in the database', 'wp-certificates') ?></td>
            </tr>
            <?php if ($current_key) : ?>
                <tr>
                    <th scope="row"><?= esc_html__('Created', 'wp-certificates') ?></th>
                    <td><?= esc_html($date($current_key['created_at'] ?? null)) ?> · <?= esc_html($user_name((int) ($current_key['created_by'] ?? 0))) ?></td>
                </tr>
            <?php endif; ?>
            <tr>
                <th scope="row"><?= esc_html__('Keys kept for verification', 'wp-certificates') ?></th>
                <td><?= (int) count($stored['keys']) ?></td>
            </tr>
        </tbody>
    </table>
    <p class="description" style="max-width:760px"><?= esc_html__('The key is never shown. Rotate it if you suspect someone could read the database: new signatures will use a new key and previous ones keep being verified with theirs.', 'wp-certificates') ?></p>
    <?php if ($uses_config) : ?>
        <p class="description"><?= esc_html__('This site signs with the key of wp-config.php; rotating here only affects the automatic key.', 'wp-certificates') ?></p>
    <?php endif; ?>
    <p><?php $form('squuad_cert_signature_rotate_key', __('Rotate key', 'wp-certificates'), 'button', __('Create a new signing key? New signatures will use it.', 'wp-certificates')); ?></p>

    <h2><?= esc_html__('Chain verification', 'wp-certificates') ?></h2>
    <?php if (!is_array($last)) : ?>
        <p><?= esc_html__('The chain has not been verified yet.', 'wp-certificates') ?></p>
    <?php else : ?>
        <p>
            <?= esc_html(sprintf(
                /* translators: 1: date, 2: user */
                __('Last verification: %1$s by %2$s.', 'wp-certificates'),
                $date($last['verified_at'] ?? null),
                $user_name((int) ($last['verified_by'] ?? 0))
            )) ?>
            <?php if (empty($last['head_ok'])) : ?>
                <strong style="color:#b32d2e"><?= esc_html__('The head of the chain does not match its last link: signatures may have been deleted.', 'wp-certificates') ?></strong>
            <?php endif; ?>
        </p>
        <table class="widefat striped" style="max-width:760px">
            <thead><tr><th><?= esc_html__('Integrity', 'wp-certificates') ?></th><th style="text-align:right"><?= esc_html__('Signatures', 'wp-certificates') ?></th></tr></thead>
            <tbody>
                <?php foreach ((array) $last['status'] as $status => $total) :
                    $alarm = in_array($status, ['altered', 'retired_key', 'chain_broken', 'unknown_key', 'missing'], true) && $total > 0; ?>
                    <tr>
                        <td><?= $alarm ? '<strong style="color:#b32d2e">' : '' ?><?= esc_html(squuad_cert_signature_integrity_label((string) $status)) ?><?= $alarm ? '</strong>' : '' ?></td>
                        <td style="text-align:right"><?= (int) $total ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <p class="description">
            <?= esc_html(sprintf(
                /* translators: 1: active signatures, 2: revoked signatures, 3: last link */
                __('%1$d active signatures, %2$d revoked (kept after a rejection), last link of the chain: %3$d.', 'wp-certificates'),
                (int) $last['live'],
                (int) $last['revoked'],
                (int) $last['last_seq']
            )) ?>
        </p>

        <h3><?= esc_html__('Context', 'wp-certificates') ?></h3>
        <table class="widefat striped" style="max-width:760px">
            <tbody>
                <tr><td><?= esc_html__('Automatic (typed name)', 'wp-certificates') ?></td><td style="text-align:right"><?= (int) $last['context']['automatic'] ?></td></tr>
                <tr><td><?= esc_html__('Signed from the account of another person', 'wp-certificates') ?></td><td style="text-align:right"><?= (int) $last['context']['other_account'] ?></td></tr>
                <tr><td><?= esc_html__('Switched session', 'wp-certificates') ?></td><td style="text-align:right"><?= (int) $last['context']['switched'] ?></td></tr>
                <tr><td><?= esc_html__('Signed on another site', 'wp-certificates') ?></td><td style="text-align:right"><?= (int) $last['context']['other_site'] ?></td></tr>
            </tbody>
        </table>

        <?php if (!empty($last['problems'])) : ?>
            <h3><?= esc_html__('Signatures to review', 'wp-certificates') ?></h3>
            <table class="widefat striped" style="max-width:960px">
                <thead><tr>
                    <th><?= esc_html__('Signature', 'wp-certificates') ?></th>
                    <th><?= esc_html__('Document', 'wp-certificates') ?></th>
                    <th><?= esc_html__('User', 'wp-certificates') ?></th>
                    <th><?= esc_html__('Document owner', 'wp-certificates') ?></th>
                    <th><?= esc_html__('Integrity', 'wp-certificates') ?></th>
                </tr></thead>
                <tbody>
                    <?php foreach ($last['problems'] as $problem) : ?>
                        <tr>
                            <td>#<?= (int) $problem['id'] ?><?= $problem['revoked'] ? ' (' . esc_html__('revoked', 'wp-certificates') . ')' : '' ?></td>
                            <td><?= esc_html($problem['document_id']) ?></td>
                            <td><?= esc_html($user_name((int) $problem['user_id'])) ?></td>
                            <td><?= !empty($problem['subject_id']) ? esc_html($user_name((int) $problem['subject_id'])) : '—' ?></td>
                            <td><strong style="color:#b32d2e"><?= esc_html(squuad_cert_signature_integrity_label($problem['status'])) ?></strong></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    <?php endif; ?>
    <p><?php $form('squuad_cert_signature_verify', __('Verify now', 'wp-certificates'), 'button button-primary'); ?></p>
    <p class="description"><?= esc_html__('Also available from the command line: wp squuad-cert firmas verificar', 'wp-certificates') ?></p>

    <h2><?= esc_html__('Legacy signatures (before the fingerprint)', 'wp-certificates') ?></h2>
    <p style="max-width:760px"><?= esc_html__('Signatures saved by the previous system (users_signatures) have no fingerprint and are only read here. Nothing is changed: this is a read-only diagnosis so each institution can decide what to do with them.', 'wp-certificates') ?></p>
    <table class="widefat striped" style="max-width:760px">
        <tbody>
            <tr><td><?= esc_html__('Legacy signatures', 'wp-certificates') ?></td><td style="text-align:right"><?= (int) count($legacy) ?></td></tr>
            <tr><td><?= esc_html__('Automatic (typed name)', 'wp-certificates') ?></td><td style="text-align:right"><?= (int) $count('automatic') ?></td></tr>
            <tr><td><?= esc_html__('User no longer exists', 'wp-certificates') ?></td><td style="text-align:right"><?= (int) $count('user_missing') ?></td></tr>
        </tbody>
    </table>
    <p><?php $form('squuad_cert_signature_legacy_csv', __('Export CSV', 'wp-certificates')); ?></p>
    <?php endif; ?>
</div>
